feat(helm-chart): Add DQL parameters to ConfigMap
iterative/helm-charts pull request #119
Opened 2023-07-13 09:19 UTC by mjasion

2023-07-13 09:30 UTC, omesser requested changes

2023-07-13 09:30 UTC, omesser commented on charts/studio/templates/configmap-studio.yaml
> +  DQL_ROOT_DIR: {{ .Values.global.dql.rootDir | default "/tmp" | quote }}
```suggestion
  DQL_ROOT_DIR: {{ .Values.global.dvcx.rootDir | default "/tmp" | quote }}
  DVCX_ROOT_DIR: {{ .Values.global.dvcx.rootDir | default "/tmp" | quote }}
```

2023-07-13 09:30 UTC, omesser commented on charts/studio/templates/configmap-studio.yaml
> +  DQL_ROOT_DIR: {{ .Values.global.dql.rootDir | default "/tmp" | quote }}
+ update  .Values.global.dql -> .Values.global.dvcx to new name

2023-07-13 13:41 UTC, omesser commented on charts/studio/values.yaml
> +  # -- Studio: Settings related to DVC^X
```suggestion
  # -- Studio: Settings related to DVCX
```
just avoiding stuff that are hard to grep 😋

2023-07-13 13:41 UTC, omesser approved these changes

2023-07-14 06:26 UTC, jesper7 requested changes
LGTM. One minor comment

2023-07-14 06:26 UTC, jesper7 commented on charts/studio/values.yaml
> +    # -- Place where DVC^X will store its temporary files
```suggestion
    # -- Place where DVCX will store its temporary files
```

Same as Oded's comment from before

2023-07-14 10:11 UTC, jesper7 submitted a review, later dismissed

2023-07-14 10:27 UTC, merged