readme - fix secret, create namespace
iterative/helm-charts pull request #39
Opened 2023-01-12 22:55 UTC by omesser

Now that the charts are installed in `studio` namespace, the `docker-registry` secret needs to be there too (otherwise referencing it the way we do doesn't work, and it should be there anyways).
- creating namespace manually first
- modifying secret creation command
- Adding pycharm metadata dir to gitignore 😃

2023-01-13 11:56 UTC, jesper7 requested changes

2023-01-13 11:56 UTC, jesper7 commented on README.md
> +Let's create it now:
```suggestion
We'll install Studio and related components in a dedicated `studio` namespace. 
Let's create it now:
```

2023-01-13 11:59 UTC, jesper7 commented
Updated the PR title so that we can start having a consistent format for README changes in the changelog

2023-01-14 15:14 UTC, mjasion approved these changes

2023-01-14 15:28 UTC, merged